theme: jekyll-theme-minimal
title: Rui's Blog
description: Write some blogs to record my learning process!

# 添加以下配置  
baseurl: "" # 如果你的博客托管在 GitHub Pages 的根目录，保持为空  
url: "https://huangruiiii.github.io" # 替换为你的 GitHub Pages URL  

# 博客文章的默认配置  
defaults:  
  - scope:  
      path: ""  
      type: "posts"  
    values:  
      layout: "post"  

# 显示未来的文章（可选）  
future: true  

# 文章的永久链接格式  
permalink: /:categories/:year/:month/:day/:title.html  
